# Generated by Django 3.2.5 on 2021-07-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can mark returned', 'Set book as returned'),)},
        ),
    ]
